- name: Check for swap file
  stat:
    path: /swapfile
  register: swap

- name: Create swap file
  command: |
    fallocate -l 1024M /swapfile
  when: swap.stat.exists == False

- name: Set swap file permissions
  file:
    path: /swapfile
    state: "file"
    owner: "root"
    group: "root"
    mode: "0600"
  when: swap.stat.exists == False

- name: Initialize swap file
  command: mkswap /swapfile
  when: swap.stat.exists == False

- name: Enable swap file
  command: swapon /swapfile
  when: swap.stat.exists == False

- name: Manage swap file in /etc/fstab
  mount:
    src: /swapfile
    name: "none"
    fstype: "swap"
    opts: "sw,nofail"
    dump: "0"
    passno: "0"
    state: present
  when: swap.stat.exists == False
