- name: Set swap_file variable
  set_fact:
    swap_file: "{{swap_file_path}}"
  tags:
    - swap.set.file.path

- name: Check if swap file exists
  stat:
    path: "{{swap_file}}"
  register: swap_file_check
  tags:
    - swap.file.check

- name: Create swap file
  become: yes
  command: fallocate -l {{swap_file_size}} {{swap_file}}
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.create
- name: Change swap file permissions
  become: yes
  file: path="{{swap_file}}"
    owner=root
    group=root
    mode=0600
  tags:
    - swap.file.permissions

- name: Format swap file
  become: yes
  command: "mkswap {{swap_file}}"
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  become: yes
  mount: name=none
    src={{swap_file}}
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present
  tags:
    - swap.fstab

- name: Turn on swap
  become: yes
  command: swapon -a
  when: not swap_file_check.stat.exists
  tags:
    - swap.turn.on

- name: Set swappiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: "{{swappiness}}"
  tags:
    - swap.set.swappiness
# http://richard.to/programming/formatting-mounting-persistent-disks-on-gce-with-ansible.html
# - name: Check if disk exists
#   shell: "file -sL /dev/disk/by-id/google-"
#   register: disk_exists
# - name: Format disk
#   shell: "mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-"
#   when: "'UUID=' not in disk_exists.stdout"
# - name: Create mount directory
#   file:
#     dest: "/mnt/disks/"
#     state: directory
#     owner: root
#     group: root
#     mode: 0755
# - name: Mount drive
#   mount:
#     path: "/mnt/disks/"
#     src: "/dev/disk/by-id/google-"
#     fstype: ext4
#     opts: discard,defaults
#     state: mounted
