- name: Install dep apt package
  apt:
    name: go-dep
  become: yes
  become_method: sudo
  # become_user: root

- name: Add golang plugin to asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git"
  register: golang_add
  failed_when: golang_add == 2

- name: Install golang {{go_version}} with asdf
  command: "${HOME}/.asdf/bin/asdf install golang {{item}}"
  loop: "{{go_versions}}"

- name: Set global version for golang to {{go_versions[0]}}
  command: "${HOME}/.asdf/bin/asdf global golang {{go_versions[0]}}"
