- name: Set up local workstation
  hosts: local
  roles:
    - role: git
      tags:
        - git
    - role: apt
      tags:
        - apt
    - role: zsh
      tags:
        - zsh
    # - role: fzf
    #   tags:
    #     - fzf
    # - role: vim
    #   tags:
    #     - vim
    - role: tmux
      tags:
        - tmux
    - role: asdf
      tags:
        - asdf
    - role: golang
      tags:
        - golang
    - role: redis
      tags:
        - redis
