package_upgrade: yes
packages:
  - build-essential
  - curl
  - docker-compose
  - docker.io
  - htop
  - jq
  - libbz2-dev
  - libffi-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  # - llvm
  - make
  - python-openssl
  - wget
  - xz-utils
  - zlib1g-dev
  - unzip
  # - ripgrep
  # - fzf
  # - tk-dev

  # GUI
  # - chromium-browser
  # - gnome-boxes
  # - gnome-icon-theme
  # - gnome-keyring
  # - i3lock
remove_packages:
  - gnome-shell-extension-ubuntu-dock
