- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~/.asdf"
    version: v0.8.0

- name: Install dep apt package
  apt:
    name: go-dep
  become: yes
  become_method: sudo
  # become_user: root

- name: Add golang plugin to asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git"
  register: golang_add
  failed_when: golang_add == 2

- name: Install golang with asdf
  command: "${HOME}/.asdf/bin/asdf install golang {{item}}"
  loop: "{{go_versions}}"

- name: Set global version for golang to {{go_versions[0]}}
  command: "${HOME}/.asdf/bin/asdf global golang {{go_versions[0]}}"

- name: Add golang plugin to asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add ghq"

- name: Install ghq with asdf
  command: "${HOME}/.asdf/bin/asdf install ghq {{item}}"
  loop: "{{ghq_versions}}"

- name: Set global version for ghq to {{ghq_versions[0]}}
  command: "${HOME}/.asdf/bin/asdf global ghq {{ghq_versions[0]}}"

- name: Set global version for golang to {{go_versions[0]}}
  command: "${HOME}/.asdf/bin/asdf reshim"
