- name: Creates directory
  file:
    path: ~/hello
    state: directory
- name: Deploy Docker daemon.json.
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
# - name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist
#   shell: ls >> somelog.txt
#   args:
#     chdir: somedir/
#     creates: somelog.txt
- name: Run expect to wait for a successful PXE boot via out-of-band CIMC
  shell: |
    mkdir $HOME/docker
    ls
    ls -la
    sudo usermod -aG docker $(whoami)
    sudo systemctl daemon-reload

# args:
# executable: /usr/bin/expect
